//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMonitor.Web.ESHour {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtStatCode;
		protected global::System.Web.UI.WebControls.TextBox txtTP;
		protected global::System.Web.UI.WebControls.TextBox txtDB;
		protected global::System.Web.UI.WebControls.TextBox txtDatatime;
		protected global::System.Web.UI.WebControls.TextBox txtWindSpeed;
		protected global::System.Web.UI.WebControls.TextBox txtRain;
		protected global::System.Web.UI.WebControls.TextBox txtWindDirection;
		protected global::System.Web.UI.WebControls.TextBox txtTemperature;
		protected global::System.Web.UI.WebControls.TextBox txtHumidity;
		protected global::System.Web.UI.WebControls.TextBox txtAirpressure;
		protected global::System.Web.UI.WebControls.TextBox txtDataStatus;
		protected global::System.Web.UI.WebControls.TextBox txtValidDataNum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
