//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMonitor.Web.ESHour {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblStatCode;
	protected global::System.Web.UI.WebControls.Label lblTP;
	protected global::System.Web.UI.WebControls.Label lblDB;
	protected global::System.Web.UI.WebControls.Label lblDatatime;
	protected global::System.Web.UI.WebControls.Label lblWindSpeed;
	protected global::System.Web.UI.WebControls.Label lblRain;
	protected global::System.Web.UI.WebControls.Label lblWindDirection;
	protected global::System.Web.UI.WebControls.Label lblTemperature;
	protected global::System.Web.UI.WebControls.Label lblHumidity;
	protected global::System.Web.UI.WebControls.Label lblAirpressure;
	protected global::System.Web.UI.WebControls.Label lblDataStatus;
	protected global::System.Web.UI.WebControls.Label lblValidDataNum;


       
    }
}
