//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMonitor.Web.Stats {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblStatCode;
	protected global::System.Web.UI.WebControls.Label lblStatName;
	protected global::System.Web.UI.WebControls.Label lblChargeMan;
	protected global::System.Web.UI.WebControls.Label lblTelepone;
	protected global::System.Web.UI.WebControls.Label lblLongitude;
	protected global::System.Web.UI.WebControls.Label lblDepartment;
	protected global::System.Web.UI.WebControls.Label lblAdress;
	protected global::System.Web.UI.WebControls.Label lblCountry;
	protected global::System.Web.UI.WebControls.Label lblStreet;
	protected global::System.Web.UI.WebControls.Label lblSquare;
	protected global::System.Web.UI.WebControls.Label lblProStartTime;
	protected global::System.Web.UI.WebControls.Label lblStage;


       
    }
}
